### ISSUE TITLE
Makefile: help target suggestion

### ISSUE THREAD

**Issue by thylong** [JulienBreux/rabdis#2]
Hey @JulienBreux !

I was hanging around your repository and while reading the `Makefile` noticed that this resource might interests you : https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html

Have a good one !

**Comment by JulienBreux** [comment]
> Hey @JulienBreux !
> 
> I was hanging around your repository and while reading the `Makefile` noticed that this resource might interests you : https://marmelab.com/blog/2016/02/29/auto-documented-makefile.html
> 
> Have a good one !

Hey!

Big thanks for the suggestion.
